import { createClient } from '@supabase/supabase-js'

// IMPORTANT: This seed uses the service_role key to create Supabase Auth users.
// The service_role key bypasses RLS and can create auth users.
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

if (!supabaseServiceKey) {
    console.error('❌ SUPABASE_SERVICE_ROLE_KEY is required for seeding.')
    console.error('   This key is needed to create users in Supabase Auth.')
    process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
    auth: { autoRefreshToken: false, persistSession: false }
})

// Store user UUIDs generated by Supabase Auth
const userIds: Record<string, string> = {}

async function createAuthUser(
    email: string,
    password: string,
    name: string,
    key: string
): Promise<string> {
    // Try to create the user in Supabase Auth
    const { data, error } = await supabase.auth.admin.createUser({
        email,
        password,
        email_confirm: true,
        user_metadata: { name }
    })

    if (error) {
        // If user already exists, try to find them
        if (error.message.includes('already been registered') || error.message.includes('already exists')) {
            const { data: { users } } = await supabase.auth.admin.listUsers()
            const existing = users?.find(u => u.email === email)
            if (existing) {
                console.log(`   ℹ️  User ${email} already exists, reusing UUID`)
                userIds[key] = existing.id
                return existing.id
            }
        }
        throw new Error(`Failed to create auth user ${email}: ${error.message}`)
    }

    const userId = data.user.id
    userIds[key] = userId
    return userId
}

async function main() {
    console.log('🌱 Starting DC Flow seed with Supabase Auth...')
    console.log(`📡 Connecting to: ${supabaseUrl}`)

    // ============================================
    // 1. CLEAN EXISTING DATA (in correct order to respect FK constraints)
    // ============================================
    console.log('\n🗑️  Cleaning existing data...')

    const tablesToClean = [
        'Annotation', 'Attachment', 'ChecklistItem', 'Checklist',
        'CustomFieldValue', 'CustomField', 'TaskRelation',
        'TimeEntry', 'Comment', 'Activity', 'TaskAssignment', 'Task',
        'Automation', 'Status', 'List', 'Folder',
        'ResourcePermission', 'Invitation', 'Document', 'Template',
        'Notification', 'NotificationPreference',
        'TeamMember', 'Team', 'SpaceMember', 'Space', 'User'
    ]

    for (const table of tablesToClean) {
        const { error } = await supabase.from(table).delete().neq('id', '___none___')
        if (error && !error.message.includes('does not exist')) {
            console.warn(`   ⚠️  Could not clean ${table}: ${error.message}`)
        }
    }
    // Clean composite-key tables separately
    await supabase.from('SpaceMember').delete().neq('spaceId', '___none___')
    await supabase.from('TeamMember').delete().neq('teamId', '___none___')

    console.log('   ✅ Cleaned existing data')

    // ============================================
    // 2. CREATE USERS IN SUPABASE AUTH + PROFILE TABLE
    // ============================================
    console.log('\n👥 Creating users in Supabase Auth...')

    const usersData = [
        // Admins
        { key: 'admin', email: 'admin@dcflow.com', name: 'Admin User', role: 'SUPER_ADMIN', userType: 'MEMBER', weeklyCapacity: 40 },

        // Creatividad / Diseño
        { key: 'maria', email: 'maria@dcflow.com', name: 'María García', role: 'ADMIN', userType: 'MEMBER', weeklyCapacity: 40 },
        { key: 'carlos', email: 'carlos@dcflow.com', name: 'Carlos Rodríguez', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },
        { key: 'camila', email: 'camila@dcflow.com', name: 'Camila Herrera', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },

        // Social Media
        { key: 'juan', email: 'juan@dcflow.com', name: 'Juan Martínez', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },
        { key: 'laura', email: 'laura@dcflow.com', name: 'Laura Fernández', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },

        // Estrategia
        { key: 'ana', email: 'ana@dcflow.com', name: 'Ana López', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },
        { key: 'diego', email: 'diego@dcflow.com', name: 'Diego Sánchez', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },

        // Cuentas
        { key: 'sofia', email: 'sofia@dcflow.com', name: 'Sofía Morales', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },
        { key: 'pablo', email: 'pablo@dcflow.com', name: 'Pablo Torres', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },

        // Producción
        { key: 'valeria', email: 'valeria@dcflow.com', name: 'Valeria Ruiz', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },
        { key: 'rodrigo', email: 'rodrigo@dcflow.com', name: 'Rodrigo Vega', role: 'MEMBER', userType: 'MEMBER', weeklyCapacity: 40 },

        // Clientes (Guests)
        { key: 'client-banco', email: 'cliente@banconacional.com', name: 'Director Marketing - Banco Nacional', role: 'MEMBER', userType: 'GUEST', weeklyCapacity: 0 },
        { key: 'client-retail', email: 'cliente@retailmax.com', name: 'Gerente Comunicaciones - RetailMax', role: 'MEMBER', userType: 'GUEST', weeklyCapacity: 0 },
    ]

    for (const userData of usersData) {
        const userId = await createAuthUser(userData.email, 'password123', userData.name, userData.key)

        const { error } = await supabase.from('User').upsert({
            id: userId,
            email: userData.email,
            name: userData.name,
            role: userData.role,
            userType: userData.userType,
            weeklyCapacity: userData.weeklyCapacity,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }, { onConflict: 'id' })

        if (error) {
            console.error(`   ❌ Error creating profile for ${userData.email}:`, error.message)
        } else {
            console.log(`   ✅ ${userData.name} (${userData.role}) → ${userId.slice(0, 8)}...`)
        }
    }

    console.log(`\n✅ Created ${usersData.length} users`)

    // ============================================
    // 3. CREATE SPACES (5 departamentos)
    // ============================================
    console.log('\n🏢 Creating spaces...')

    const spaces = [
        { id: 'space-brand', name: 'Brand', slug: 'brand', color: '#E67E22', icon: '✦', description: 'Identidad visual, naming y brand guidelines' },
        { id: 'space-estrategia', name: 'Estrategia', slug: 'estrategia', color: '#9B59B6', icon: '🎯', description: 'Planificación estratégica, research e insights' },
        { id: 'space-creatividad', name: 'Creatividad', slug: 'creatividad', color: '#F2A6A6', icon: '🎨', description: 'Departamento de diseño y creatividad' },
        { id: 'space-social', name: 'Redes Sociales', slug: 'redes-sociales', color: '#17385C', icon: '📱', description: 'Gestión de redes sociales y contenido digital' },
        { id: 'space-produccion', name: 'Producción', slug: 'produccion', color: '#0F4036', icon: '🎬', description: 'Producción audiovisual y eventos' },
    ]

    for (const space of spaces) {
        await supabase.from('Space').upsert({
            ...space,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }, { onConflict: 'slug' })
    }

    console.log(`✅ Created ${spaces.length} spaces`)

    // ============================================
    // 4. ADD SPACE MEMBERS (using dynamic UUIDs)
    // ============================================
    console.log('\n👥 Adding space members...')

    const spaceMembers = [
        // Brand
        { spaceId: 'space-brand', userId: userIds['admin'], role: 'OWNER' },
        { spaceId: 'space-brand', userId: userIds['maria'], role: 'ADMIN' },
        { spaceId: 'space-brand', userId: userIds['carlos'], role: 'MEMBER' },
        { spaceId: 'space-brand', userId: userIds['camila'], role: 'MEMBER' },

        // Estrategia
        { spaceId: 'space-estrategia', userId: userIds['admin'], role: 'OWNER' },
        { spaceId: 'space-estrategia', userId: userIds['ana'], role: 'ADMIN' },
        { spaceId: 'space-estrategia', userId: userIds['diego'], role: 'MEMBER' },
        { spaceId: 'space-estrategia', userId: userIds['sofia'], role: 'MEMBER' },

        // Creatividad
        { spaceId: 'space-creatividad', userId: userIds['admin'], role: 'OWNER' },
        { spaceId: 'space-creatividad', userId: userIds['maria'], role: 'ADMIN' },
        { spaceId: 'space-creatividad', userId: userIds['carlos'], role: 'MEMBER' },
        { spaceId: 'space-creatividad', userId: userIds['camila'], role: 'MEMBER' },
        { spaceId: 'space-creatividad', userId: userIds['ana'], role: 'MEMBER' },

        // Redes Sociales
        { spaceId: 'space-social', userId: userIds['admin'], role: 'OWNER' },
        { spaceId: 'space-social', userId: userIds['juan'], role: 'ADMIN' },
        { spaceId: 'space-social', userId: userIds['laura'], role: 'MEMBER' },

        // Producción
        { spaceId: 'space-produccion', userId: userIds['admin'], role: 'OWNER' },
        { spaceId: 'space-produccion', userId: userIds['valeria'], role: 'ADMIN' },
        { spaceId: 'space-produccion', userId: userIds['rodrigo'], role: 'MEMBER' },
        { spaceId: 'space-produccion', userId: userIds['carlos'], role: 'MEMBER' },
    ]

    for (const member of spaceMembers) {
        await supabase.from('SpaceMember').upsert(member, { onConflict: 'spaceId,userId' })
    }

    console.log(`✅ Added ${spaceMembers.length} space members`)

    // ============================================
    // 5. CREATE STATUSES FOR EACH SPACE
    // ============================================
    console.log('\n📊 Creating statuses...')

    const statuses = [
        // Brand
        { id: 'status-brand-brief', name: 'Brief Recibido', color: '#DFE1E6', order: 1, type: 'TODO', spaceId: 'space-brand' },
        { id: 'status-brand-design', name: 'En Diseño', color: '#E67E22', order: 2, type: 'IN_PROGRESS', spaceId: 'space-brand' },
        { id: 'status-brand-review', name: 'Revisión Cliente', color: '#F39C12', order: 3, type: 'IN_PROGRESS', spaceId: 'space-brand' },
        { id: 'status-brand-done', name: 'Aprobado', color: '#27AE60', order: 4, type: 'DONE', spaceId: 'space-brand' },

        // Estrategia
        { id: 'status-est-research', name: 'Investigación', color: '#DFE1E6', order: 1, type: 'TODO', spaceId: 'space-estrategia' },
        { id: 'status-est-analysis', name: 'Análisis', color: '#9B59B6', order: 2, type: 'IN_PROGRESS', spaceId: 'space-estrategia' },
        { id: 'status-est-present', name: 'Presentación', color: '#8E44AD', order: 3, type: 'IN_PROGRESS', spaceId: 'space-estrategia' },
        { id: 'status-est-done', name: 'Aprobado', color: '#27AE60', order: 4, type: 'DONE', spaceId: 'space-estrategia' },

        // Creatividad
        { id: 'status-cre-todo', name: 'Por Hacer', color: '#DFE1E6', order: 1, type: 'TODO', spaceId: 'space-creatividad' },
        { id: 'status-cre-progress', name: 'En Proceso', color: '#F2A6A6', order: 2, type: 'IN_PROGRESS', spaceId: 'space-creatividad' },
        { id: 'status-cre-review', name: 'En Revisión', color: '#17385C', order: 3, type: 'IN_PROGRESS', spaceId: 'space-creatividad' },
        { id: 'status-cre-done', name: 'Completado', color: '#0F4036', order: 4, type: 'DONE', spaceId: 'space-creatividad' },

        // Redes Sociales
        { id: 'status-soc-draft', name: 'Borrador', color: '#DFE1E6', order: 1, type: 'TODO', spaceId: 'space-social' },
        { id: 'status-soc-scheduled', name: 'Programado', color: '#17385C', order: 2, type: 'IN_PROGRESS', spaceId: 'space-social' },
        { id: 'status-soc-published', name: 'Publicado', color: '#0F4036', order: 3, type: 'DONE', spaceId: 'space-social' },

        // Producción
        { id: 'status-prod-prep', name: 'Pre-producción', color: '#DFE1E6', order: 1, type: 'TODO', spaceId: 'space-produccion' },
        { id: 'status-prod-filming', name: 'Filmación', color: '#F2A6A6', order: 2, type: 'IN_PROGRESS', spaceId: 'space-produccion' },
        { id: 'status-prod-edit', name: 'Edición', color: '#17385C', order: 3, type: 'IN_PROGRESS', spaceId: 'space-produccion' },
        { id: 'status-prod-delivered', name: 'Entregado', color: '#0F4036', order: 4, type: 'DONE', spaceId: 'space-produccion' },
    ]

    for (const status of statuses) {
        await supabase.from('Status').upsert(status)
    }

    console.log(`✅ Created ${statuses.length} statuses`)

    // ============================================
    // 6. CREATE FOLDERS
    // ============================================
    console.log('\n📁 Creating folders...')

    const folders = [
        // Brand
        { id: 'folder-banco-brand', name: 'Banco Nacional', spaceId: 'space-brand', color: '#17385C' },
        { id: 'folder-retail-brand', name: 'RetailMax', spaceId: 'space-brand', color: '#E67E22' },

        // Estrategia
        { id: 'folder-banco-estrategia', name: 'Banco Nacional', spaceId: 'space-estrategia', color: '#17385C' },
        { id: 'folder-retail-estrategia', name: 'RetailMax', spaceId: 'space-estrategia', color: '#9B59B6' },

        // Creatividad
        { id: 'folder-banco', name: 'Banco Nacional', spaceId: 'space-creatividad', color: '#17385C' },
        { id: 'folder-retail', name: 'RetailMax', spaceId: 'space-creatividad', color: '#F2A6A6' },

        // Redes Sociales
        { id: 'folder-banco-social', name: 'Banco Nacional', spaceId: 'space-social', color: '#17385C' },
        { id: 'folder-retail-social', name: 'RetailMax', spaceId: 'space-social', color: '#F2A6A6' },
    ]

    for (const folder of folders) {
        await supabase.from('Folder').upsert({
            ...folder,
            useCustomStatus: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${folders.length} folders`)

    // ============================================
    // 7. CREATE LISTS
    // ============================================
    console.log('\n📋 Creating lists...')

    const lists = [
        // Brand
        { id: 'list-manual-marca', name: 'Manual de Marca Banco Nacional', description: 'Documentación completa de identidad visual', spaceId: 'space-brand', folderId: 'folder-banco-brand' },
        { id: 'list-rebranding-retail', name: 'Rebranding RetailMax', description: 'Actualización completa de identidad de marca', spaceId: 'space-brand', folderId: 'folder-retail-brand' },
        { id: 'list-naming-fintech', name: 'Naming Startup Fintech', description: 'Propuesta de naming para nuevo cliente fintech', spaceId: 'space-brand', folderId: null, isPitch: true, pitchDate: '2026-03-15', pitchResult: 'PENDING' },

        // Estrategia
        { id: 'list-plan-q1', name: 'Plan Estratégico Q1 2026', description: 'Planificación estratégica primer trimestre', spaceId: 'space-estrategia', folderId: 'folder-banco-estrategia' },
        { id: 'list-research-retail', name: 'Research Competitivo RetailMax', description: 'Análisis de mercado y competencia', spaceId: 'space-estrategia', folderId: 'folder-retail-estrategia' },
        { id: 'list-insights', name: 'Insights de Consumidor', description: 'Investigación y hallazgos sobre audiencias', spaceId: 'space-estrategia', folderId: null },

        // Creatividad
        { id: 'list-campaign-verano', name: 'Campaña Verano 2026', description: 'Campaña de marketing para la temporada de verano', spaceId: 'space-creatividad', folderId: 'folder-banco' },
        { id: 'list-branding', name: 'Rediseño de Marca', description: 'Actualización de identidad visual', spaceId: 'space-creatividad', folderId: 'folder-retail' },
        { id: 'list-pitch-tech', name: 'Pitch TechCorp', description: 'Propuesta para nuevo cliente tecnología', spaceId: 'space-creatividad', folderId: null, isPitch: true, pitchDate: '2026-02-28', pitchResult: 'PENDING' },

        // Redes Sociales
        { id: 'list-social-banco', name: 'Contenido Febrero', description: 'Plan de contenidos para redes del banco', spaceId: 'space-social', folderId: 'folder-banco-social' },
        { id: 'list-social-retail', name: 'Lanzamiento Producto', description: 'Campaña de lanzamiento en redes', spaceId: 'space-social', folderId: 'folder-retail-social' },

        // Producción
        { id: 'list-video-institucional', name: 'Video Institucional', description: 'Video corporativo para Banco Nacional', spaceId: 'space-produccion', folderId: null },
    ]

    for (const list of lists) {
        await supabase.from('List').upsert({
            ...list,
            isPitch: list.isPitch || false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${lists.length} lists`)

    // ============================================
    // 8. CREATE TASKS
    // ============================================
    console.log('\n✅ Creating tasks...')

    const tasks = [
        // ── Brand: Manual de Marca Banco Nacional ──
        { id: 'task-20', title: 'Guía de colores y tipografía', description: 'Definir paleta de colores primarios/secundarios y selección tipográfica', listId: 'list-manual-marca', statusId: 'status-brand-design', priority: 'HIGH', dueDate: '2026-02-25', estimatedHours: 12, createdById: userIds['maria'] },
        { id: 'task-21', title: 'Templates de presentaciones', description: 'Crear plantillas de PowerPoint y Google Slides con identidad', listId: 'list-manual-marca', statusId: 'status-brand-brief', priority: 'NORMAL', dueDate: '2026-03-05', estimatedHours: 8, createdById: userIds['maria'] },
        { id: 'task-22', title: 'Papelería corporativa', description: 'Diseño de tarjetas, sobres, carpetas y hojas membretadas', listId: 'list-manual-marca', statusId: 'status-brand-brief', priority: 'NORMAL', dueDate: '2026-03-10', estimatedHours: 10, createdById: userIds['maria'] },

        // ── Brand: Rebranding RetailMax ──
        { id: 'task-23', title: 'Auditoría de marca actual', description: 'Análisis completo de la identidad visual existente', listId: 'list-rebranding-retail', statusId: 'status-brand-done', priority: 'HIGH', dueDate: '2026-01-25', estimatedHours: 8, createdById: userIds['camila'], completedAt: '2026-01-24T16:00:00Z' },
        { id: 'task-24', title: 'Propuestas de nueva identidad', description: 'Crear 3 direcciones creativas para la nueva marca', listId: 'list-rebranding-retail', statusId: 'status-brand-design', priority: 'HIGH', dueDate: '2026-02-20', estimatedHours: 20, createdById: userIds['camila'] },
        { id: 'task-25', title: 'Diseño de logotipo actualizado', description: 'Desarrollo final del logotipo seleccionado', listId: 'list-rebranding-retail', statusId: 'status-brand-brief', priority: 'URGENT', dueDate: '2026-03-01', estimatedHours: 16, createdById: userIds['maria'] },

        // ── Brand: Naming Startup Fintech ──
        { id: 'task-26', title: 'Investigación lingüística', description: 'Análisis de disponibilidad de nombres y dominios', listId: 'list-naming-fintech', statusId: 'status-brand-done', priority: 'URGENT', estimatedHours: 6, createdById: userIds['ana'], completedAt: '2026-02-05T14:00:00Z' },
        { id: 'task-27', title: 'Propuestas de nombres', description: 'Generar 10 opciones de naming con justificación estratégica', listId: 'list-naming-fintech', statusId: 'status-brand-design', priority: 'HIGH', dueDate: '2026-02-28', estimatedHours: 8, createdById: userIds['ana'] },

        // ── Estrategia: Plan Estratégico Q1 2026 ──
        { id: 'task-28', title: 'Análisis FODA Banco Nacional', description: 'Diagnóstico de fortalezas, debilidades, oportunidades y amenazas', listId: 'list-plan-q1', statusId: 'status-est-done', priority: 'HIGH', dueDate: '2026-01-20', estimatedHours: 8, createdById: userIds['ana'], completedAt: '2026-01-19T17:00:00Z' },
        { id: 'task-29', title: 'Definición de KPIs Q1', description: 'Establecer métricas clave por área para el trimestre', listId: 'list-plan-q1', statusId: 'status-est-analysis', priority: 'URGENT', dueDate: '2026-02-15', estimatedHours: 6, createdById: userIds['ana'] },
        { id: 'task-30', title: 'Presentación estrategia a directorio', description: 'Preparar y presentar plan ante el board del cliente', listId: 'list-plan-q1', statusId: 'status-est-research', priority: 'HIGH', dueDate: '2026-03-01', estimatedHours: 10, createdById: userIds['diego'] },

        // ── Estrategia: Research Competitivo RetailMax ──
        { id: 'task-31', title: 'Benchmark competidores', description: 'Análisis detallado de 5 principales competidores', listId: 'list-research-retail', statusId: 'status-est-done', priority: 'NORMAL', dueDate: '2026-01-30', estimatedHours: 12, createdById: userIds['diego'], completedAt: '2026-01-29T15:00:00Z' },
        { id: 'task-32', title: 'Análisis tendencias retail 2026', description: 'Investigar tendencias de mercado y comportamiento del consumidor', listId: 'list-research-retail', statusId: 'status-est-analysis', priority: 'HIGH', dueDate: '2026-02-20', estimatedHours: 10, createdById: userIds['ana'] },
        { id: 'task-33', title: 'Mapeo de customer journey', description: 'Documentar recorrido del cliente en todos los touchpoints', listId: 'list-research-retail', statusId: 'status-est-research', priority: 'NORMAL', dueDate: '2026-03-05', estimatedHours: 14, createdById: userIds['diego'] },

        // ── Estrategia: Insights de Consumidor ──
        { id: 'task-34', title: 'Preparación focus group', description: 'Diseñar guía de preguntas y reclutar participantes', listId: 'list-insights', statusId: 'status-est-analysis', priority: 'HIGH', dueDate: '2026-02-22', estimatedHours: 8, createdById: userIds['ana'] },
        { id: 'task-35', title: 'Informe insights Q4 2025', description: 'Compilar hallazgos y recomendaciones del trimestre anterior', listId: 'list-insights', statusId: 'status-est-done', priority: 'NORMAL', estimatedHours: 6, createdById: userIds['ana'], completedAt: '2026-01-15T11:00:00Z' },

        // ── Creatividad: Campaña Verano 2026 ──
        { id: 'task-1', title: 'Diseñar key visual principal', description: 'Crear el concepto visual principal de la campaña', listId: 'list-campaign-verano', statusId: 'status-cre-progress', priority: 'HIGH', dueDate: '2026-02-20', estimatedHours: 16, createdById: userIds['admin'] },
        { id: 'task-2', title: 'Redactar copy para redes sociales', description: 'Crear textos para posts de Instagram, Facebook y LinkedIn', listId: 'list-campaign-verano', statusId: 'status-cre-todo', priority: 'NORMAL', dueDate: '2026-02-28', estimatedHours: 8, createdById: userIds['admin'] },
        { id: 'task-3', title: 'Presentación a cliente', description: 'Preparar deck de presentación con propuestas', listId: 'list-campaign-verano', statusId: 'status-cre-review', priority: 'URGENT', dueDate: '2026-02-14', estimatedHours: 4, createdById: userIds['admin'] },
        { id: 'task-4', title: 'Revisar feedback del cliente', description: 'Incorporar comentarios de la última reunión', listId: 'list-campaign-verano', statusId: 'status-cre-todo', priority: 'HIGH', parentId: 'task-3', createdById: userIds['admin'] },

        // ── Creatividad: Rediseño de Marca ──
        { id: 'task-5', title: 'Análisis de competencia', description: 'Investigar tendencias y competidores', listId: 'list-branding', statusId: 'status-cre-done', priority: 'NORMAL', dueDate: '2026-01-25', estimatedHours: 8, createdById: userIds['maria'], completedAt: '2026-01-24T10:00:00Z' },
        { id: 'task-6', title: 'Propuestas de logo', description: 'Crear 3 opciones de logo', listId: 'list-branding', statusId: 'status-cre-progress', priority: 'HIGH', dueDate: '2026-02-25', estimatedHours: 20, createdById: userIds['maria'] },
        { id: 'task-7', title: 'Manual de marca', description: 'Documentar guías de uso', listId: 'list-branding', statusId: 'status-cre-todo', priority: 'NORMAL', dueDate: '2026-03-10', estimatedHours: 12, createdById: userIds['maria'] },

        // ── Creatividad: Pitch TechCorp ──
        { id: 'task-8', title: 'Investigación del cliente', description: 'Entender necesidades y objetivos', listId: 'list-pitch-tech', statusId: 'status-cre-done', priority: 'URGENT', estimatedHours: 4, createdById: userIds['ana'], completedAt: '2026-02-02T15:00:00Z' },
        { id: 'task-9', title: 'Estrategia creativa', description: 'Definir concepto y approach', listId: 'list-pitch-tech', statusId: 'status-cre-progress', priority: 'URGENT', dueDate: '2026-02-18', estimatedHours: 8, createdById: userIds['ana'] },
        { id: 'task-10', title: 'Deck de presentación', description: 'Armar presentación final', listId: 'list-pitch-tech', statusId: 'status-cre-todo', priority: 'URGENT', dueDate: '2026-02-26', estimatedHours: 6, createdById: userIds['maria'] },

        // ── Redes Sociales: Contenido Febrero ──
        { id: 'task-11', title: 'Post: Tips financieros', description: 'Carrusel educativo sobre ahorro', listId: 'list-social-banco', statusId: 'status-soc-published', priority: 'NORMAL', dueDate: '2026-02-05', estimatedHours: 2, createdById: userIds['juan'], completedAt: '2026-02-05T09:00:00Z' },
        { id: 'task-12', title: 'Post: Nuevo producto', description: 'Anuncio de cuenta de ahorro', listId: 'list-social-banco', statusId: 'status-soc-scheduled', priority: 'HIGH', dueDate: '2026-02-12', estimatedHours: 3, createdById: userIds['juan'] },
        { id: 'task-13', title: 'Stories: Behind the scenes', description: 'Contenido informal del equipo', listId: 'list-social-banco', statusId: 'status-soc-draft', priority: 'LOW', dueDate: '2026-02-15', estimatedHours: 1, createdById: userIds['laura'] },

        // ── Redes Sociales: Lanzamiento Producto ──
        { id: 'task-14', title: 'Teaser campaña', description: 'Post de expectativa pre-lanzamiento', listId: 'list-social-retail', statusId: 'status-soc-published', priority: 'HIGH', dueDate: '2026-01-20', estimatedHours: 2, createdById: userIds['laura'], completedAt: '2026-01-20T11:00:00Z' },
        { id: 'task-15', title: 'Post lanzamiento', description: 'Anuncio oficial del producto', listId: 'list-social-retail', statusId: 'status-soc-scheduled', priority: 'URGENT', dueDate: '2026-02-10', estimatedHours: 3, createdById: userIds['juan'] },
        { id: 'task-16', title: 'Reels promocional', description: 'Video corto para Instagram', listId: 'list-social-retail', statusId: 'status-soc-draft', priority: 'HIGH', dueDate: '2026-02-14', estimatedHours: 4, createdById: userIds['laura'] },

        // ── Producción: Video Institucional ──
        { id: 'task-17', title: 'Guión y storyboard', description: 'Escribir guión y planificar tomas', listId: 'list-video-institucional', statusId: 'status-prod-filming', priority: 'HIGH', dueDate: '2026-02-18', estimatedHours: 10, createdById: userIds['valeria'] },
        { id: 'task-18', title: 'Casting y locaciones', description: 'Seleccionar actores y lugares', listId: 'list-video-institucional', statusId: 'status-prod-prep', priority: 'NORMAL', dueDate: '2026-02-22', estimatedHours: 6, createdById: userIds['valeria'] },
        { id: 'task-19', title: 'Filmación día 1', description: 'Grabar escenas en oficina', listId: 'list-video-institucional', statusId: 'status-prod-prep', priority: 'HIGH', dueDate: '2026-03-01', estimatedHours: 8, createdById: userIds['valeria'] },
    ]

    for (const task of tasks) {
        await supabase.from('Task').upsert({
            ...task,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${tasks.length} tasks`)

    // ============================================
    // 9. CREATE TASK ASSIGNMENTS
    // ============================================
    console.log('\n👤 Creating task assignments...')

    const assignments = [
        // Brand: Manual de Marca
        { id: 'assign-30', taskId: 'task-20', userId: userIds['maria'] },
        { id: 'assign-31', taskId: 'task-21', userId: userIds['camila'] },
        { id: 'assign-32', taskId: 'task-22', userId: userIds['camila'] },

        // Brand: Rebranding RetailMax
        { id: 'assign-33', taskId: 'task-23', userId: userIds['camila'] },
        { id: 'assign-34', taskId: 'task-24', userId: userIds['camila'] },
        { id: 'assign-35', taskId: 'task-24', userId: userIds['carlos'] },
        { id: 'assign-36', taskId: 'task-25', userId: userIds['carlos'] },

        // Brand: Naming Fintech
        { id: 'assign-37', taskId: 'task-26', userId: userIds['ana'] },
        { id: 'assign-38', taskId: 'task-27', userId: userIds['ana'] },
        { id: 'assign-39', taskId: 'task-27', userId: userIds['camila'] },

        // Estrategia: Plan Q1
        { id: 'assign-40', taskId: 'task-28', userId: userIds['ana'] },
        { id: 'assign-41', taskId: 'task-29', userId: userIds['diego'] },
        { id: 'assign-42', taskId: 'task-30', userId: userIds['ana'] },
        { id: 'assign-43', taskId: 'task-30', userId: userIds['diego'] },

        // Estrategia: Research RetailMax
        { id: 'assign-44', taskId: 'task-31', userId: userIds['diego'] },
        { id: 'assign-45', taskId: 'task-32', userId: userIds['ana'] },
        { id: 'assign-46', taskId: 'task-33', userId: userIds['diego'] },
        { id: 'assign-47', taskId: 'task-33', userId: userIds['sofia'] },

        // Estrategia: Insights
        { id: 'assign-48', taskId: 'task-34', userId: userIds['ana'] },
        { id: 'assign-49', taskId: 'task-34', userId: userIds['diego'] },
        { id: 'assign-50', taskId: 'task-35', userId: userIds['ana'] },

        // Creatividad: Campaña Verano
        { id: 'assign-1', taskId: 'task-1', userId: userIds['maria'] },
        { id: 'assign-2', taskId: 'task-2', userId: userIds['juan'] },
        { id: 'assign-3', taskId: 'task-3', userId: userIds['maria'] },
        { id: 'assign-4', taskId: 'task-3', userId: userIds['ana'] },
        { id: 'assign-5', taskId: 'task-4', userId: userIds['ana'] },

        // Creatividad: Rediseño de Marca
        { id: 'assign-6', taskId: 'task-5', userId: userIds['ana'] },
        { id: 'assign-7', taskId: 'task-6', userId: userIds['carlos'] },
        { id: 'assign-8', taskId: 'task-7', userId: userIds['maria'] },

        // Creatividad: Pitch TechCorp
        { id: 'assign-9', taskId: 'task-8', userId: userIds['ana'] },
        { id: 'assign-10', taskId: 'task-9', userId: userIds['ana'] },
        { id: 'assign-11', taskId: 'task-9', userId: userIds['diego'] },
        { id: 'assign-12', taskId: 'task-10', userId: userIds['maria'] },

        // Redes Sociales
        { id: 'assign-13', taskId: 'task-11', userId: userIds['juan'] },
        { id: 'assign-14', taskId: 'task-12', userId: userIds['juan'] },
        { id: 'assign-15', taskId: 'task-13', userId: userIds['laura'] },
        { id: 'assign-16', taskId: 'task-14', userId: userIds['laura'] },
        { id: 'assign-17', taskId: 'task-15', userId: userIds['juan'] },
        { id: 'assign-18', taskId: 'task-16', userId: userIds['laura'] },

        // Producción
        { id: 'assign-19', taskId: 'task-17', userId: userIds['valeria'] },
        { id: 'assign-20', taskId: 'task-18', userId: userIds['valeria'] },
        { id: 'assign-21', taskId: 'task-18', userId: userIds['rodrigo'] },
        { id: 'assign-22', taskId: 'task-19', userId: userIds['valeria'] },
        { id: 'assign-23', taskId: 'task-19', userId: userIds['rodrigo'] },
    ]

    for (const assignment of assignments) {
        await supabase.from('TaskAssignment').upsert({
            ...assignment,
            assignedAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${assignments.length} task assignments`)

    // ============================================
    // 10. CREATE TEAMS
    // ============================================
    console.log('\n👥 Creating teams...')

    const teams = [
        { id: 'team-diseno', name: 'Diseño', description: 'Equipo de diseñadores gráficos', color: '#F2A6A6' },
        { id: 'team-social', name: 'Social Media', description: 'Community managers y content creators', color: '#17385C' },
        { id: 'team-cuentas', name: 'Cuentas', description: 'Account managers', color: '#0F4036' },
        { id: 'team-estrategia', name: 'Estrategia', description: 'Planners y estrategas', color: '#9B59B6' },
        { id: 'team-produccion', name: 'Producción', description: 'Producción audiovisual y eventos', color: '#2C3E50' },
    ]

    for (const team of teams) {
        await supabase.from('Team').upsert({
            ...team,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        })
    }

    const teamMembers = [
        // Diseño
        { teamId: 'team-diseno', userId: userIds['maria'], role: 'LEAD' },
        { teamId: 'team-diseno', userId: userIds['carlos'], role: 'MEMBER' },
        { teamId: 'team-diseno', userId: userIds['camila'], role: 'MEMBER' },

        // Social Media
        { teamId: 'team-social', userId: userIds['juan'], role: 'LEAD' },
        { teamId: 'team-social', userId: userIds['laura'], role: 'MEMBER' },

        // Cuentas
        { teamId: 'team-cuentas', userId: userIds['sofia'], role: 'LEAD' },
        { teamId: 'team-cuentas', userId: userIds['pablo'], role: 'MEMBER' },

        // Estrategia
        { teamId: 'team-estrategia', userId: userIds['ana'], role: 'LEAD' },
        { teamId: 'team-estrategia', userId: userIds['diego'], role: 'MEMBER' },

        // Producción
        { teamId: 'team-produccion', userId: userIds['valeria'], role: 'LEAD' },
        { teamId: 'team-produccion', userId: userIds['rodrigo'], role: 'MEMBER' },
    ]

    for (const member of teamMembers) {
        await supabase.from('TeamMember').upsert({
            ...member,
            joinedAt: new Date().toISOString(),
        }, { onConflict: 'teamId,userId' })
    }

    console.log(`✅ Created ${teams.length} teams with ${teamMembers.length} members`)

    // ============================================
    // 11. CREATE COMMENTS
    // ============================================
    console.log('\n💬 Creating comments...')

    const comments = [
        { id: 'comment-1', taskId: 'task-1', userId: userIds['maria'], content: 'Ya tengo el primer boceto listo, lo subo en 1 hora' },
        { id: 'comment-2', taskId: 'task-1', userId: userIds['admin'], content: '@María García perfecto, avísame cuando esté para revisarlo' },
        { id: 'comment-3', taskId: 'task-6', userId: userIds['carlos'], content: 'Necesito feedback sobre la paleta de colores' },
        { id: 'comment-4', taskId: 'task-9', userId: userIds['diego'], content: 'Investigué sobre su competencia, muy interesante el mercado' },
        { id: 'comment-5', taskId: 'task-15', userId: userIds['juan'], content: 'El copy está listo, falta aprobación del cliente' },
        { id: 'comment-6', taskId: 'task-24', userId: userIds['camila'], content: 'Tengo 2 de las 3 direcciones listas. La tercera va por un enfoque más minimalista' },
        { id: 'comment-7', taskId: 'task-24', userId: userIds['maria'], content: 'Me gusta la dirección minimalista, creo que va más con lo que busca el cliente' },
        { id: 'comment-8', taskId: 'task-29', userId: userIds['diego'], content: 'Los KPIs de awareness deberían incluir share of voice este trimestre' },
        { id: 'comment-9', taskId: 'task-32', userId: userIds['ana'], content: 'El informe de Euromonitor tiene datos muy relevantes, lo agrego como referencia' },
        { id: 'comment-10', taskId: 'task-17', userId: userIds['valeria'], content: 'El guión va por la versión 3, el cliente pidió un tono más cercano' },
    ]

    for (const comment of comments) {
        await supabase.from('Comment').upsert({
            ...comment,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${comments.length} comments`)

    // ============================================
    // 12. CREATE TIME ENTRIES
    // ============================================
    console.log('\n⏱️  Creating time entries...')

    const timeEntries = [
        // Creatividad
        { id: 'time-1', taskId: 'task-1', userId: userIds['maria'], hours: 4.5, date: '2026-02-10', description: 'Investigación y bocetos iniciales' },
        { id: 'time-2', taskId: 'task-3', userId: userIds['ana'], hours: 2, date: '2026-02-12', description: 'Armado de presentación' },
        { id: 'time-3', taskId: 'task-5', userId: userIds['ana'], hours: 8, date: '2026-01-23', description: 'Análisis completo de competencia' },
        { id: 'time-4', taskId: 'task-6', userId: userIds['carlos'], hours: 6, date: '2026-02-14', description: 'Bocetos de logo - opción 1 y 2' },

        // Social
        { id: 'time-5', taskId: 'task-11', userId: userIds['juan'], hours: 2, date: '2026-02-04', description: 'Redacción y diseño de carrusel' },
        { id: 'time-6', taskId: 'task-14', userId: userIds['laura'], hours: 1.5, date: '2026-01-19', description: 'Creación de teaser' },

        // Brand
        { id: 'time-7', taskId: 'task-23', userId: userIds['camila'], hours: 8, date: '2026-01-22', description: 'Auditoría completa de marca existente' },
        { id: 'time-8', taskId: 'task-24', userId: userIds['camila'], hours: 5, date: '2026-02-12', description: 'Dirección creativa 1 - Concepto "Evolución"' },
        { id: 'time-9', taskId: 'task-24', userId: userIds['carlos'], hours: 4, date: '2026-02-13', description: 'Dirección creativa 2 - Concepto "Raíces"' },
        { id: 'time-10', taskId: 'task-20', userId: userIds['maria'], hours: 3, date: '2026-02-15', description: 'Selección de paleta de colores' },

        // Estrategia
        { id: 'time-11', taskId: 'task-28', userId: userIds['ana'], hours: 8, date: '2026-01-18', description: 'Análisis FODA completo' },
        { id: 'time-12', taskId: 'task-31', userId: userIds['diego'], hours: 12, date: '2026-01-28', description: 'Benchmark de 5 competidores' },
        { id: 'time-13', taskId: 'task-29', userId: userIds['diego'], hours: 3, date: '2026-02-10', description: 'Definición de KPIs financieros' },
        { id: 'time-14', taskId: 'task-34', userId: userIds['ana'], hours: 2, date: '2026-02-16', description: 'Guía de preguntas para focus group' },

        // Producción
        { id: 'time-15', taskId: 'task-17', userId: userIds['valeria'], hours: 6, date: '2026-02-14', description: 'Escritura de guión v1 y v2' },
        { id: 'time-16', taskId: 'task-17', userId: userIds['rodrigo'], hours: 3, date: '2026-02-15', description: 'Storyboard escenas 1-5' },
    ]

    for (const entry of timeEntries) {
        await supabase.from('TimeEntry').upsert({
            ...entry,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${timeEntries.length} time entries`)

    // ============================================
    // 13. CREATE CHECKLISTS
    // ============================================
    console.log('\n☑️  Creating checklists...')

    const checklists = [
        { id: 'checklist-1', name: 'Preparación presentación', taskId: 'task-3', order: 0 },
        { id: 'checklist-2', name: 'Pre-producción video', taskId: 'task-17', order: 0 },
        { id: 'checklist-3', name: 'Entregables identidad', taskId: 'task-24', order: 0 },
        { id: 'checklist-4', name: 'KPIs por área', taskId: 'task-29', order: 0 },
    ]

    for (const checklist of checklists) {
        await supabase.from('Checklist').upsert({
            ...checklist,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        })
    }

    const checklistItems = [
        // Preparación presentación (task-3)
        { id: 'cli-1', content: 'Diseñar slides', isCompleted: true, checklistId: 'checklist-1', order: 0, completedAt: '2026-02-12T14:00:00Z', completedById: userIds['maria'] },
        { id: 'cli-2', content: 'Revisar copy', isCompleted: true, checklistId: 'checklist-1', order: 1, completedAt: '2026-02-13T10:00:00Z', completedById: userIds['ana'] },
        { id: 'cli-3', content: 'Preparar mockups', isCompleted: false, checklistId: 'checklist-1', order: 2, assigneeId: userIds['carlos'] },
        { id: 'cli-4', content: 'Ensayar presentación', isCompleted: false, checklistId: 'checklist-1', order: 3, dueDate: '2026-02-14' },

        // Pre-producción video (task-17)
        { id: 'cli-5', content: 'Escribir guión', isCompleted: true, checklistId: 'checklist-2', order: 0, completedAt: '2026-02-14T16:00:00Z', completedById: userIds['valeria'] },
        { id: 'cli-6', content: 'Storyboard completo', isCompleted: false, checklistId: 'checklist-2', order: 1, assigneeId: userIds['rodrigo'], dueDate: '2026-02-18' },
        { id: 'cli-7', content: 'Aprobar guión con cliente', isCompleted: false, checklistId: 'checklist-2', order: 2, assigneeId: userIds['valeria'] },
        { id: 'cli-8', content: 'Definir locaciones', isCompleted: false, checklistId: 'checklist-2', order: 3, assigneeId: userIds['rodrigo'] },

        // Entregables identidad (task-24)
        { id: 'cli-9', content: 'Paleta de colores', isCompleted: true, checklistId: 'checklist-3', order: 0, completedAt: '2026-02-10T11:00:00Z', completedById: userIds['camila'] },
        { id: 'cli-10', content: 'Tipografía principal y secundaria', isCompleted: true, checklistId: 'checklist-3', order: 1, completedAt: '2026-02-11T15:00:00Z', completedById: userIds['camila'] },
        { id: 'cli-11', content: 'Iconografía', isCompleted: false, checklistId: 'checklist-3', order: 2, assigneeId: userIds['carlos'] },
        { id: 'cli-12', content: 'Mockups de aplicación', isCompleted: false, checklistId: 'checklist-3', order: 3, assigneeId: userIds['camila'], dueDate: '2026-02-20' },

        // KPIs por área (task-29)
        { id: 'cli-13', content: 'KPIs financieros', isCompleted: true, checklistId: 'checklist-4', order: 0, completedAt: '2026-02-10T09:00:00Z', completedById: userIds['diego'] },
        { id: 'cli-14', content: 'KPIs de awareness', isCompleted: false, checklistId: 'checklist-4', order: 1, assigneeId: userIds['diego'] },
        { id: 'cli-15', content: 'KPIs de engagement', isCompleted: false, checklistId: 'checklist-4', order: 2, assigneeId: userIds['ana'] },
        { id: 'cli-16', content: 'KPIs de conversión', isCompleted: false, checklistId: 'checklist-4', order: 3, assigneeId: userIds['diego'] },
    ]

    for (const item of checklistItems) {
        await supabase.from('ChecklistItem').upsert({
            ...item,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${checklists.length} checklists with ${checklistItems.length} items`)

    // ============================================
    // 14. CREATE ACTIVITIES (audit trail)
    // ============================================
    console.log('\n📝 Creating activities...')

    const activities = [
        // task-1: Key visual
        { id: 'act-1', taskId: 'task-1', userId: userIds['admin'], type: 'CREATED', createdAt: '2026-02-05T09:00:00Z' },
        { id: 'act-2', taskId: 'task-1', userId: userIds['admin'], type: 'ASSIGNED', field: 'assignee', newValue: userIds['maria'], createdAt: '2026-02-05T09:01:00Z' },
        { id: 'act-3', taskId: 'task-1', userId: userIds['maria'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'Por Hacer', newValue: 'En Proceso', createdAt: '2026-02-08T10:00:00Z' },

        // task-5: Análisis competencia (completed)
        { id: 'act-4', taskId: 'task-5', userId: userIds['maria'], type: 'CREATED', createdAt: '2026-01-15T09:00:00Z' },
        { id: 'act-5', taskId: 'task-5', userId: userIds['ana'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'Por Hacer', newValue: 'En Proceso', createdAt: '2026-01-20T10:00:00Z' },
        { id: 'act-6', taskId: 'task-5', userId: userIds['ana'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'En Proceso', newValue: 'Completado', createdAt: '2026-01-24T10:00:00Z' },

        // task-23: Auditoría de marca (completed)
        { id: 'act-7', taskId: 'task-23', userId: userIds['camila'], type: 'CREATED', createdAt: '2026-01-15T09:00:00Z' },
        { id: 'act-8', taskId: 'task-23', userId: userIds['camila'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'Brief Recibido', newValue: 'En Diseño', createdAt: '2026-01-18T10:00:00Z' },
        { id: 'act-9', taskId: 'task-23', userId: userIds['camila'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'En Diseño', newValue: 'Aprobado', createdAt: '2026-01-24T16:00:00Z' },

        // task-24: Propuestas nueva identidad
        { id: 'act-10', taskId: 'task-24', userId: userIds['camila'], type: 'CREATED', createdAt: '2026-01-25T09:00:00Z' },
        { id: 'act-11', taskId: 'task-24', userId: userIds['camila'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'Brief Recibido', newValue: 'En Diseño', createdAt: '2026-02-05T10:00:00Z' },
        { id: 'act-12', taskId: 'task-24', userId: userIds['maria'], type: 'COMMENT_ADDED', createdAt: '2026-02-13T11:00:00Z' },

        // task-28: FODA (completed)
        { id: 'act-13', taskId: 'task-28', userId: userIds['ana'], type: 'CREATED', createdAt: '2026-01-10T09:00:00Z' },
        { id: 'act-14', taskId: 'task-28', userId: userIds['ana'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'Investigación', newValue: 'Análisis', createdAt: '2026-01-15T10:00:00Z' },
        { id: 'act-15', taskId: 'task-28', userId: userIds['ana'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'Análisis', newValue: 'Aprobado', createdAt: '2026-01-19T17:00:00Z' },

        // task-17: Guión y storyboard
        { id: 'act-16', taskId: 'task-17', userId: userIds['valeria'], type: 'CREATED', createdAt: '2026-02-01T09:00:00Z' },
        { id: 'act-17', taskId: 'task-17', userId: userIds['valeria'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'Pre-producción', newValue: 'Filmación', createdAt: '2026-02-14T10:00:00Z' },
        { id: 'act-18', taskId: 'task-17', userId: userIds['valeria'], type: 'COMMENT_ADDED', createdAt: '2026-02-16T14:00:00Z' },

        // task-11: Post publicado
        { id: 'act-19', taskId: 'task-11', userId: userIds['juan'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'Borrador', newValue: 'Programado', createdAt: '2026-02-03T10:00:00Z' },
        { id: 'act-20', taskId: 'task-11', userId: userIds['juan'], type: 'STATUS_CHANGED', field: 'status', oldValue: 'Programado', newValue: 'Publicado', createdAt: '2026-02-05T09:00:00Z' },
    ]

    for (const activity of activities) {
        await supabase.from('Activity').upsert(activity)
    }

    console.log(`✅ Created ${activities.length} activities`)

    // ============================================
    // 15. CREATE DOCUMENTS (briefs)
    // ============================================
    console.log('\n📄 Creating documents...')

    const documents = [
        {
            id: 'doc-1',
            title: 'Brief Campaña Verano 2026',
            content: JSON.stringify({
                type: 'doc',
                content: [
                    { type: 'heading', content: 'Campaña Verano 2026 - Banco Nacional' },
                    { type: 'paragraph', content: 'Objetivo: Aumentar captaciones en un 15% durante temporada estival.' },
                    { type: 'paragraph', content: 'Target: Adultos 25-45, NSE ABC1. Tono: cercano pero profesional.' },
                    { type: 'heading', content: 'Entregables' },
                    { type: 'paragraph', content: '- Key visual principal\n- 8 piezas para RRSS\n- Banner web\n- Email marketing (3 envíos)' },
                ]
            }),
            emoji: '☀️',
            listId: 'list-campaign-verano',
            spaceId: 'space-creatividad',
            isPublic: false,
            isFavorite: true,
            isArchived: false,
            createdById: userIds['sofia'],
        },
        {
            id: 'doc-2',
            title: 'Brand Guidelines RetailMax',
            content: JSON.stringify({
                type: 'doc',
                content: [
                    { type: 'heading', content: 'RetailMax - Guía de Marca' },
                    { type: 'paragraph', content: 'Este documento establece los lineamientos de identidad visual para RetailMax.' },
                    { type: 'heading', content: 'Misión de Marca' },
                    { type: 'paragraph', content: 'Ser la marca retail más cercana y confiable de Chile.' },
                    { type: 'heading', content: 'Valores' },
                    { type: 'paragraph', content: '- Cercanía\n- Innovación\n- Calidad\n- Sustentabilidad' },
                ]
            }),
            emoji: '✦',
            listId: 'list-rebranding-retail',
            spaceId: 'space-brand',
            isPublic: false,
            isFavorite: false,
            isArchived: false,
            createdById: userIds['camila'],
        },
        {
            id: 'doc-3',
            title: 'Plan Estratégico Q1 2026',
            content: JSON.stringify({
                type: 'doc',
                content: [
                    { type: 'heading', content: 'Plan Estratégico Q1 2026 - Banco Nacional' },
                    { type: 'paragraph', content: 'Período: Enero - Marzo 2026' },
                    { type: 'heading', content: 'Objetivos Estratégicos' },
                    { type: 'paragraph', content: '1. Aumentar awareness de marca en segmento joven\n2. Lanzar campaña de verano con foco digital\n3. Consolidar presencia en LinkedIn B2B' },
                    { type: 'heading', content: 'KPIs Principales' },
                    { type: 'paragraph', content: '- Reach mensual: 500K\n- Engagement rate: >3.5%\n- Leads generados: 200/mes\n- NPS: >45' },
                ]
            }),
            emoji: '🎯',
            listId: 'list-plan-q1',
            spaceId: 'space-estrategia',
            isPublic: false,
            isFavorite: true,
            isArchived: false,
            createdById: userIds['ana'],
        },
    ]

    for (const doc of documents) {
        await supabase.from('Document').upsert({
            ...doc,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${documents.length} documents`)

    // ============================================
    // 16. CREATE NOTIFICATIONS
    // ============================================
    console.log('\n🔔 Creating notifications...')

    const notifications = [
        { id: 'notif-1', type: 'TASK_ASSIGNED', userId: userIds['maria'], actorId: userIds['admin'], taskId: 'task-1', title: 'Nueva tarea asignada', message: 'Admin te asignó "Diseñar key visual principal"' },
        { id: 'notif-2', type: 'COMMENT_ADDED', userId: userIds['carlos'], actorId: userIds['maria'], taskId: 'task-6', title: 'Nuevo comentario', message: 'María comentó en "Propuestas de logo"' },
        { id: 'notif-3', type: 'DUE_DATE_SOON', userId: userIds['ana'], taskId: 'task-9', title: 'Fecha límite próxima', message: '"Estrategia creativa" vence el 18 de febrero' },
        { id: 'notif-4', type: 'STATUS_CHANGED', userId: userIds['camila'], actorId: userIds['maria'], taskId: 'task-24', title: 'Cambio de estado', message: '"Propuestas de nueva identidad" pasó a En Diseño' },
        { id: 'notif-5', type: 'TASK_COMPLETED', userId: userIds['admin'], actorId: userIds['ana'], taskId: 'task-28', title: 'Tarea completada', message: 'Ana completó "Análisis FODA Banco Nacional"' },
        { id: 'notif-6', type: 'DUE_DATE_SOON', userId: userIds['valeria'], taskId: 'task-17', title: 'Fecha límite próxima', message: '"Guión y storyboard" vence hoy' },
        { id: 'notif-7', type: 'COMMENT_ADDED', userId: userIds['camila'], actorId: userIds['carlos'], taskId: 'task-24', title: 'Nuevo comentario', message: 'Carlos comentó en "Propuestas de nueva identidad"' },
        { id: 'notif-8', type: 'MENTION', userId: userIds['maria'], actorId: userIds['admin'], taskId: 'task-1', title: 'Te mencionaron', message: 'Admin te mencionó en "Diseñar key visual principal"' },
    ]

    for (const notification of notifications) {
        await supabase.from('Notification').upsert({
            ...notification,
            isRead: false,
            createdAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${notifications.length} notifications`)

    // ============================================
    // 17. CREATE RESOURCE PERMISSIONS
    // ============================================
    console.log('\n🔐 Creating permissions...')

    const permissions = [
        // Clientes guest con acceso limitado
        { id: 'perm-1', userId: userIds['client-banco'], listId: 'list-campaign-verano', level: 'READ_ONLY', grantedById: userIds['admin'] },
        { id: 'perm-2', userId: userIds['client-banco'], listId: 'list-social-banco', level: 'COMMENT', grantedById: userIds['admin'] },
        { id: 'perm-3', userId: userIds['client-retail'], listId: 'list-branding', level: 'READ_ONLY', grantedById: userIds['admin'] },
        { id: 'perm-4', userId: userIds['client-retail'], listId: 'list-social-retail', level: 'COMMENT', grantedById: userIds['admin'] },
        { id: 'perm-5', userId: userIds['client-banco'], listId: 'list-manual-marca', level: 'COMMENT', grantedById: userIds['admin'] },
        { id: 'perm-6', userId: userIds['client-retail'], listId: 'list-rebranding-retail', level: 'COMMENT', grantedById: userIds['admin'] },
        { id: 'perm-7', userId: userIds['client-banco'], listId: 'list-plan-q1', level: 'READ_ONLY', grantedById: userIds['admin'] },
    ]

    for (const permission of permissions) {
        await supabase.from('ResourcePermission').upsert({
            ...permission,
            grantedAt: new Date().toISOString(),
        })
    }

    console.log(`✅ Created ${permissions.length} permissions`)

    // ============================================
    // SUMMARY
    // ============================================
    console.log('\n🎉 Seed completed successfully!')
    console.log('\n📊 Summary:')
    console.log(`   - ${usersData.length} users (created in Supabase Auth + User table)`)
    console.log(`   - ${spaces.length} spaces (Brand, Estrategia, Creatividad, Redes Sociales, Producción)`)
    console.log(`   - ${spaceMembers.length} space members`)
    console.log(`   - ${statuses.length} statuses`)
    console.log(`   - ${folders.length} folders`)
    console.log(`   - ${lists.length} lists`)
    console.log(`   - ${tasks.length} tasks`)
    console.log(`   - ${assignments.length} task assignments`)
    console.log(`   - ${checklists.length} checklists with ${checklistItems.length} items`)
    console.log(`   - ${activities.length} activities`)
    console.log(`   - ${documents.length} documents`)
    console.log(`   - ${comments.length} comments`)
    console.log(`   - ${timeEntries.length} time entries`)
    console.log(`   - ${teams.length} teams with ${teamMembers.length} members`)
    console.log(`   - ${notifications.length} notifications`)
    console.log(`   - ${permissions.length} resource permissions`)
    console.log('\n🔑 Test credentials (all users share the same password):')
    console.log('   Password: password123')
    console.log('\n👤 Login as:')
    console.log('   Admin:      admin@dcflow.com')
    console.log('   Diseño:     maria@dcflow.com / carlos@dcflow.com / camila@dcflow.com')
    console.log('   Social:     juan@dcflow.com / laura@dcflow.com')
    console.log('   Estrategia: ana@dcflow.com / diego@dcflow.com')
    console.log('   Cuentas:    sofia@dcflow.com / pablo@dcflow.com')
    console.log('   Producción: valeria@dcflow.com / rodrigo@dcflow.com')
    console.log('   Cliente:    cliente@banconacional.com / cliente@retailmax.com')
}

main()
    .catch((e) => {
        console.error('❌ Error during seed:', e)
        process.exit(1)
    })
